<?php

namespace DoctrineProxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaksi extends \App\Entity\Transaksi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'pelanggan', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'kendaraan', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'tanggalSewa', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'tanggalKembali', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'lamaSewa', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'totalHarga', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'status'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'pelanggan', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'kendaraan', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'tanggalSewa', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'tanggalKembali', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'lamaSewa', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'totalHarga', '' . "\0" . 'App\\Entity\\Transaksi' . "\0" . 'status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaksi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getPelanggan(): \App\Entity\Pelanggan
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPelanggan', []);

        return parent::getPelanggan();
    }

    /**
     * {@inheritDoc}
     */
    public function getKendaraan(): \App\Entity\Kendaraan
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKendaraan', []);

        return parent::getKendaraan();
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalSewa(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalSewa', []);

        return parent::getTanggalSewa();
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalKembali(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalKembali', []);

        return parent::getTanggalKembali();
    }

    /**
     * {@inheritDoc}
     */
    public function getLamaSewa(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLamaSewa', []);

        return parent::getLamaSewa();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalHarga(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalHarga', []);

        return parent::getTotalHarga();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\User $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$v]);

        return parent::setUser($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setPelanggan(\App\Entity\Pelanggan $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPelanggan', [$v]);

        return parent::setPelanggan($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setKendaraan(\App\Entity\Kendaraan $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKendaraan', [$v]);

        return parent::setKendaraan($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalSewa(\DateTime $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalSewa', [$v]);

        return parent::setTanggalSewa($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalKembali(\DateTime $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalKembali', [$v]);

        return parent::setTanggalKembali($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setLamaSewa(int $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLamaSewa', [$v]);

        return parent::setLamaSewa($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalHarga(string $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalHarga', [$v]);

        return parent::setTotalHarga($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$v]);

        return parent::setStatus($v);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
